irisdata<-read.csv("iris.csv")
irisdata
names(irisdata)[1]<-paste("sepal_length")
names(irisdata)[2]<-paste("sepal_width")
names(irisdata)[3]<-paste("petal_length")
names(irisdata)[4]<-paste("petal_width")
names(irisdata)[5]<-paste("class")
irisdata
View(irisdata)
str(irisdata)
summary(irisdata) 
kmeans_sepal = data.frame(irisdata$sepal_length, irisdata$sepal_width)
kmeans_petal = data.frame(irisdata$petal_length,irisdata$petal_width)
sepal = kmeans(kmeans_sepal,3)
clusplot(irisdata, sepal$cluster, color = TRUE, shade = TRUE, labels = 5, lines = 0)
petal = kmeans(kmeans_petal,4)
clusplot(irisdata, petal$cluster, color = TRUE, shade = TRUE, labels = 5, lines = 0)
install.packages("cluster")
library(cluster)
