lenses<-read.csv("lenses.csv",FALSE)
lenses
str(lenses)
lenses<-lenses[-c(1)]
lenses
names(lenses)
names(lenses)[names(lenses)=="V2"]<-"Age"
names(lenses)
names(lenses)<-gsub("V3","Prescription", names(lenses))
names(lenses)
names(lenses)<-gsub("V4","Astigmatism", names(lenses))
names(lenses)
names(lenses)<-gsub("V5","Tears",names(lenses))
names(lenses)
names(lenses)<-gsub("V6","Classification",names(lenses))
names(lenses)
lenses
lenses$Age<-replace(lenses$Age,lenses$Age==1,'Young')
lenses$Age<-replace(lenses$Age,lenses$Age==2,'Adult')
lenses$Age<-replace(lenses$Age,lenses$Age==3,'Old')
lenses
lenses$Prescription<-replace(lenses$Prescription,lenses$Prescription==1,'nearsightedness')
lenses$Prescription<-replace(lenses$Prescription,lenses$Prescription==2,'farsightedness')
lenses
lenses$Astigmatism<-replace(lenses$Astigmatism,lenses$Astigmatism==1,'astigmatic')
lenses$Astigmatism<-replace(lenses$Astigmatism,lenses$Astigmatism==2,'non-astigmatic')
lenses
lenses$Tears<-replace(lenses$Tears,lenses$Tears==1,'Reduced')
lenses$Tears<-replace(lenses$Tears,lenses$Tears==2,'Normal')
lenses
lenses$Classification<-replace(lenses$Classification,lenses$Classification==1,'Hard')
lenses$Classification<-replace(lenses$Classification,lenses$Classification==2,'Soft')
lenses$Classification<-replace(lenses$Classification,lenses$Classification==3,'None')
lenses
summary(lenses)
install.packages("C50")
library(C50)
lenses_train<-lenses[1:20,]
lenses_test<-lenses[21:24,]
nrow(lenses_train)
nrow(lenses_test)
require(C50)
str(lenses)
set.seed(10203)
str(lenses)
str(lenses_train)
str(lenses_test)
dim(lenses_test)
dim(lenses_train)
View(lenses)
lenses_train$Classification<-as.factor(lenses_train$Classification)
lenses_train$Age<-as.factor(lenses_train$Age)
lenses_train$Prescription<-as.factor(lenses_train$Prescription)
lenses_train$Astigmatism<-as.factor(lenses_train$Astigmatism)
lenses_train$Tears<-as.factor(lenses_train$Tears)
lenses_test$Age<-as.factor(lenses_test$Age)
lenses_test$Prescription<-as.factor(lenses_test$Prescription)
lenses_test$Astigmatism<-as.factor(lenses_test$Astigmatism)
lenses_test$Tears<-as.factor(lenses_test$Tears)
lenses_test$Classification<-as.factor(lenses_test$Classification)
lenses1<-as.data.frame(lenses)
str(lenses1)
m<-C5.0(lenses_train[-5],lenses_train$Classification)
m
summary(m)
p<-predict(m,lenses[21:24,])
p
table(lenses[21:24,1],p)
plot(m)
install.packages("gmodels")
library(gmodels)
CrossTable(lenses_test$Classification, p)

